-- THE REPORT EXPORT (2026-09-20). Ruth's brief: "The PDF export should not feel
-- like downloading data. It should feel like building a story for a specific
-- purpose." The report is assembled from the pieces she chooses, rendered with
-- her own session, and stored here for fifteen minutes so a browser with no
-- identity can fetch it and print it.
--
-- The same shape as me_exports, and for the same reasons: no read policy at
-- all, because nothing may read a report except get_report, which can do
-- nothing else; the id is generated by the route rather than returned by the
-- insert, since PostgREST would need read access to hand it back.
create table if not exists public.report_exports (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  html text not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '15 minutes')
);

alter table public.report_exports enable row level security;

create policy "report_exports_insert_own" on public.report_exports
  for insert to authenticated with check (auth.uid() = user_id);

-- Erasure: a person may remove their own copies, and the count before account
-- deletion must not report them as left behind.
create policy "report_exports_delete_own" on public.report_exports
  for delete to authenticated using (auth.uid() = user_id);

create or replace function public.get_report(report_id uuid)
returns text
language sql
stable
security definer
set search_path = public
as $$
  select html from public.report_exports
  where id = report_id and expires_at > now()
  limit 1;
$$;

revoke all on function public.get_report(uuid) from public;
grant execute on function public.get_report(uuid) to anon, authenticated;

create or replace function public.purge_expired_report_exports()
returns void
language sql
security definer
set search_path = public
as $$
  delete from public.report_exports where expires_at < now();
$$;

revoke all on function public.purge_expired_report_exports() from public;
grant execute on function public.purge_expired_report_exports() to authenticated;
